### PR TITLE
Added the clang dependency for Fedora/RHEL systems

### PR DESCRIPTION
**Pull request by AlexonOliveiraRH**
If the `clang` package is not present, the following error occurs when running the informed command:

```
$ mkdir -p build && cd build && cmake .. && make -s
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/alolivei/GitHub/myrepos/nchat/build/CMakeFiles/CMakeOutput.log".
See also "/home/alolivei/GitHub/myrepos/nchat/build/CMakeFiles/CMakeError.log".
```

### CODE REVIEW

**Comment by AlexonOliveiraRH** [comment]
Also added the `clang` dependency, otherwise the following error occurs:

```
$ cmake .. && make -s
-- Using build type 'Release' (default).
-- Dummy: ON
-- Telegram: ON
-- WhatsApp: ON
-- Dynamic Load: ON
bash: go: command not found
CMake Warning at CMakeLists.txt:58 (message):
  Go version (need v1.18 to build WhatsApp).


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindSQLite3.cmake:54 (find_package_handle_standard_args)
  lib/ncutil/CMakeLists.txt:18 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/alolivei/GitHub/myrepos/nchat/build/CMakeFiles/CMakeOutput.log".
```

**Comment by AlexonOliveiraRH** [comment]
Also added the `libsqlite3x-devel`, `libsqlite3x` and `libsq3-devel` packages as dependencies, otherwise the following error message is shown:

```
$ cmake .. && make -s
-- Using build type 'Release' (default).
-- Dummy: ON
-- Telegram: ON
-- WhatsApp: ON
-- Dynamic Load: ON
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindSQLite3.cmake:54 (find_package_handle_standard_args)
  lib/ncutil/CMakeLists.txt:18 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/alolivei/GitHub/myrepos/nchat/build/CMakeFiles/CMakeOutput.log".
```

**Comment by d99kris** [comment]
Thanks for contributing @AlexonOliveiraRH - I will proceed to merge this into an integration branch where I'll make some follow-up fixes before merging to master. Will update here once in master.

**Comment by d99kris** [comment]
Thanks again @AlexonOliveiraRH - the Fedora dependency update has been merged to master in 3d392ad.

I made some adjustments, please let me know if you think the final documentation is not correct.

Also, the `make.sh` script has been updated to cover Fedora, so one can do:
```
./make.sh deps
./make.sh build
./make.sh install
```
to install dependencies, build and install nchat.

**Comment by AlexonOliveiraRH** [comment]
> Thanks for contributing @AlexonOliveiraRH - I will proceed to merge this into an integration branch where I'll make some follow-up fixes before merging to master. Will update here once in master.

Hey Kristofer. Thank you for accepting my contributions. I see you've made some changes in the code and it seems to be OK now.

**Comment by AlexonOliveiraRH** [comment]
> Thanks again @AlexonOliveiraRH - the Fedora dependency update has been merged to master in [3d392ad](https://github.com/d99kris/nchat/commit/3d392ad919f443ae60f04b2f7a00685dcaa73aec).
> 
> I made some adjustments, please let me know if you think the final documentation is not correct.
> 
> Also, the `make.sh` script has been updated to cover Fedora, so one can do:
> 
> ```
> ./make.sh deps
> ./make.sh build
> ./make.sh install
> ```
> 
> to install dependencies, build and install nchat.

Great, thank you so much. I also saw you adjusted the `README.md` with the correct dependencies now. Thank you for merging this.

**Pull request merged**
