### PR TITLE
update readme.md: add docs executable permission to ./make.sh

### PR DESCRIPTION
**Pull request by 99702**

### CODE REVIEW

**Comment by d99kris** [comment]
Hi @99702 - thanks for contributing, but I don't quite see why this change would be needed. Could you please help explain in which scenario `make.sh` would not have executable permission?

**Comment by 99702** [comment]
Hi @d99kris  , in new linux system after cloning , we often get `.sh` files with permission `-rw-r--r--.` or not executable.
In order to run we need to provide `chmod +x` executable permission to file, I had same problem faced, so I thought it would be nice to have command right in docs.

**Comment by d99kris** [comment]
Ideally I'd like to keep the basic build instructions very brief and simple, so if this only affects a small minority of users, I would maybe prefer to add an FAQ entry instead. But before doing even that, I'd be curious to know in what actual environment one would encounter this. Would you mind sharing distro name (can be retrieved with `grep PRETTY_NAME /etc/os-release`) and filesystem type (can get with `df -Th /` - assuming no dedicated home partition)?

**Comment by 99702** [comment]
Oh, Its okay. 

Here is my system information: 
```
df -Th / 
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/nvme0n1p3 xfs   237G   59G  178G  25% /

```


```
grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Fedora Linux 40 (Xfce)"

```

Thank you.

**Pull request closed without merging**
