### PR TITLE
Default to XDG dir for configuration

### PR DESCRIPTION
**Pull request by torrca**
This patch changes the default configuration directory, internally referred to as `ApplicationDir`, to comply with XDG's Base Directory Specification.

Most Unix tools already operate on the specification. By adhering it, Nchat becomes more intuitive and integrated with the system.

More information about the spec can be found at:
    https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

The `--confdir` flag doesn't cover this scenario as it's directed at customization at invokation and not at defaults.

Wasn't sure whether to open an issue as per the contribution [guide](https://github.com/d99kris/nchat/blob/8f7b24e9406aaa58b7d3a962428ac46f01633de3/CONTRIBUTING.md) since this change isn't exactly a bug or feature.

### CODE REVIEW

**Comment by d99kris** [comment]
Hi @torrca - thanks for contributing! 👍 

Yes, this request has come up a couple of times before, so this is welcome. 

The only issue I can see is handling of "backward compatibility", i.e. allowing existing users to upgrade to latest nchat without needing to take any action. I can probably look into that on my side, as I have an idea how I'd like to handle it. Will try to come back to this PR soonish, this weekend or next.

**Comment by torrca** [comment]
> I can probably look into that on my side, as I have an idea how I'd like to handle it. Will try to come back to this PR soonish, this weekend or next.

Thumbs up.

Lemme know if all goes well.

**Comment by d99kris** [comment]
Thanks for fixing backward compatibility! The PR generally looks fine. 👍 
I'd like some minor refactoring and documentation updates, but I'll merge the PR to a branch first and make the follow-up changes there, before finally merging all to master.

**Comment by d99kris** [comment]
FYI - the integration branch has been merged to master now as well.

**Comment by torrca** [comment]
Cheers

**Pull request merged**
