### PR TITLE
Build fix: Add various missing headers

### PR DESCRIPTION
**Pull request by alarixnia**

### CODE REVIEW

**Comment by d99kris** [comment]
Hi @alarixnia - thanks for contributing. 👍 
The PR looks good, I target to merge it in the weekend.

Out of curiosity, for which OS (or compiler) does it fix the build?

**Comment by alarixnia** [comment]
> Hi @alarixnia - thanks for contributing. 👍 The PR looks good, I target to merge it in the weekend.
> 
> Out of curiosity, for which OS (or compiler) does it fix the build?

Hi, I'm working on a package of nchat for pkgsrc. In pkgsrc we try to support every Unix-like platform, but we have a special focus on NetBSD, Solaris/illumos, Darwin, and Enterprise Linux.

This helps building on NetBSD 10.0 amd64 with GCC 10.

**Comment by d99kris** [comment]
Thanks for sharing 👍

**Comment by d99kris** [comment]
This has been merged via an integration branch to master now. Thanks again for the contribution! 👍

**Pull request merged**
